# Generated by Django 5.0.3 on 2024-06-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dias',
            fields=[
                ('idDia', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=15)),
            ],
        ),
    ]
