# Generated by Django 5.0.3 on 2024-06-25 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACyD', '0001_initial'),
        ('Empleado', '0003_documentosempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesCD',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=25)),
                ('cupo', models.IntegerField()),
                ('idDia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACyD.dias')),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACyD.horarios')),
                ('idMaestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleados')),
            ],
        ),
    ]
