# Generated by Django 5.0.3 on 2024-06-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACyD', '0002_actividadescd'),
        ('Empleado', '0003_documentosempleado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActividadesCD',
            new_name='Actividades',
        ),
    ]
