# Generated by Django 5.0.3 on 2024-06-28 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACyD', '0003_rename_actividadescd_actividades'),
        ('Alumno', '0003_estatusalumnos_grupos_alumnos'),
        ('Empleado', '0003_documentosempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividadesACyD',
            fields=[
                ('idActividadACyD', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=25)),
                ('cupo', models.IntegerField()),
                ('idDia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACyD.dias')),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACyD.horarios')),
                ('idMaestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleados')),
                ('idPeriodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='asignacionesACyD',
            fields=[
                ('idAsignacionACyD', models.AutoField(primary_key=True, serialize=False)),
                ('idDia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACyD.dias')),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.grupos')),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACyD.horarios')),
                ('idPeriodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.periodo')),
            ],
        ),
        migrations.DeleteModel(
            name='Actividades',
        ),
    ]
