# Generated by Django 5.0.3 on 2024-06-28 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACyD', '0004_actividadesacyd_asignacionesacyd_delete_actividades'),
        ('Alumno', '0003_estatusalumnos_grupos_alumnos'),
        ('Empleado', '0003_documentosempleado'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='idGrupo',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='gruposIngles',
            fields=[
                ('idGrupoIngles', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.SmallIntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('idMaestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleados')),
                ('idPeriodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='inscripciones',
            fields=[
                ('idInscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInscripcion', models.DateField()),
                ('movimiento', models.SmallIntegerField()),
                ('idPlanEstudios', models.SmallIntegerField()),
                ('IdGrupoIngles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.gruposingles')),
                ('idActividadACyD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACyD.actividadesacyd')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.alumnos')),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.grupos')),
                ('idPeriodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.periodo')),
                ('idUsuarioInscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuarios')),
            ],
        ),
    ]
